Repository gcfbn/learning_rust, pull requests merged in 2021-08, with the labels that each got.

#87 PositiveInteger: follow-up
  graphs/Cargo.lock
  utils/Cargo.lock
  utils/Cargo.toml
  utils/src/lib.rs
  utils/src/positive_integer.rs
Labels: enhancement, refactoring

#88 Fix Clippy warning - remove redundant 'Ok()' and '?'
  graphs/runner/src/generate_graph.rs
Labels: refactoring

#89 Add benchmarks for Kruskal's algorithm
  graphs/algorithms/benches/kruskal_algorithm.rs
  graphs/algorithms/benches/results.md
  graphs/algorithms/src/kruskal.rs
  graphs/graph/src/structures.rs
  graphs/makefile
Labels: enhancement

#90 Fix PositiveInteger::sub method
  utils/src/positive_integer.rs
Labels: bug

#94 Add PositiveInteger::new method
  utils/src/positive_integer.rs
Labels: enhancement

#96 Implement finding shortest path algorithm
  graphs/Cargo.lock
  graphs/algorithms/Cargo.toml
  graphs/algorithms/src/dijkstra.rs
  graphs/algorithms/src/lib.rs
  graphs/algorithms/tests/acceptance_tests.rs
  graphs/graph/src/adjacency_list.rs
  graphs/graph/src/dfs.rs
  graphs/graph/src/lib.rs
  graphs/graph/src/structures.rs
  utils/src/positive_integer.rs
Labels: enhancement, test

#105 Pdodev path validator
  graphs/graph/src/reader.rs
  graphs/runner/src/subcommands/run_algorithm.rs
  utils/src/lib.rs
  utils/src/path_validators.rs
Labels: enhancement, refactoring

#107 Add #[cfg(test)] for PositiveInteger::new
  utils/src/positive_integer.rs
Labels: refactoring

#106 String newtype
  string-newtype/Cargo.lock
  string-newtype/Cargo.toml
  string-newtype/src/lib.rs
Labels: enhancement

#111 Refactoring in tests
  string-newtype/src/lib.rs
Labels: refactoring, test

#112 Numeric newtype
  newtypes/Cargo.lock
  newtypes/Cargo.toml
  newtypes/src/lib.rs
  newtypes/src/num_newtype.rs
  newtypes/src/string_newtype.rs
Labels: enhancement

#114 Extend the default logger configuration
  utils/Cargo.lock
  utils/Cargo.toml
  utils/examples/use_default_logging/main.rs
  utils/src/application_runner.rs
Labels: bug

#117 Clean up clippy warnings + add rustfmt.toml + some tiny adjustments
  utils/examples/use_logger_with_state/main.rs
  utils/rustfmt.toml
  utils/src/application_runner.rs
  utils/src/positive_integer.rs
Labels: refactoring
