Repository gcfbn/learning_rust, pull requests merged in 2021-07, with the labels that each got.

#34 Change some dir names
  graphs/Cargo.lock
  graphs/Cargo.toml
  graphs/algorithms/Cargo.toml
  graphs/algorithms/src/kruskal.rs
  graphs/algorithms/src/lib.rs
  graphs/algorithms/tests/acceptance_tests.rs
  graphs/algorithms/tests/data/passing1.txt
  graphs/algorithms/tests/data/passing2.txt
  graphs/algorithms/tests/data/passing3.txt
  graphs/algorithms/tests/data/passing4.txt
  graphs/algorithms/tests/data/passing5.txt
  graphs/algorithms/tests/data/passing6.txt
  graphs/algorithms/tests/data/passing7.txt
  graphs/algorithms/tests/data/passing8.txt
  graphs/graph/Cargo.toml
  graphs/graph/src/dfs.rs
  graphs/graph/src/errors.rs
  graphs/graph/src/lib.rs
  graphs/graph/src/reader.rs
  graphs/graph/src/structures.rs
  graphs/graph/tests/acceptance_tests.rs
  graphs/graph/tests/data/edge_errors/error_adding_edge_too_many_edges.txt
  graphs/graph/tests/data/edge_errors/error_adding_edge_wrong_from_index.txt
  graphs/graph/tests/data/edge_errors/error_adding_edge_wrong_to_index.txt
  graphs/graph/tests/data/edge_errors/error_parsing_edge_empty_line.txt
  graphs/graph/tests/data/edge_errors/error_parsing_edge_missing_to_index.txt
  graphs/graph/tests/data/edge_errors/error_parsing_edge_missing_weight.txt
  graphs/graph/tests/data/edge_errors/error_parsing_edge_non_integer_from_index.txt
  graphs/graph/tests/data/edge_errors/error_parsing_edge_non_integer_to_index.txt
  graphs/graph/tests/data/edge_errors/error_parsing_edge_non_integer_weight.txt
  graphs/graph/tests/data/graph_building_errors/error_graph_not_connected.txt
  graphs/graph/tests/data/graph_building_errors/error_too_few_edges.txt
  graphs/graph/tests/data/parsing_graph_parameters_errors/error_parsing_graph_parameters_edges_count.txt
  graphs/graph/tests/data/parsing_graph_parameters_errors/error_parsing_graph_parameters_empty_input.txt
  graphs/graph/tests/data/parsing_graph_parameters_errors/error_parsing_graph_parameters_missing_edges_count.txt
  graphs/graph/tests/data/parsing_graph_parameters_errors/error_parsing_graph_parameters_nodes_count.txt
  graphs/runner/Cargo.toml
  graphs/runner/src/main.rs
  graphs/rustfmt.toml
  graphs/task.txt
Labels: refactoring

#41 Add documentation to the project
  graphs/algorithms/src/kruskal.rs
  graphs/algorithms/src/lib.rs
  graphs/graph/src/dfs.rs
  graphs/graph/src/errors.rs
  graphs/graph/src/lib.rs
  graphs/graph/src/reader.rs
  graphs/makefile
  graphs/runner/src/main.rs
Labels: documentation

#51 Pdo refactoring in acceptance tests v5
  graphs/graph/src/errors.rs
  graphs/graph/src/structures.rs
  graphs/graph/tests/acceptance_tests.rs
  graphs/makefile
Labels: refactoring

#47 Small refactoring in acceptance_tests.rs
  graphs/graph/tests/acceptance_tests.rs
Labels: refactoring

#48 Pdo refactoring in acceptance tests v2
  graphs/graph/tests/acceptance_tests.rs
Labels: refactoring

#49 Pdo refactoring in acceptance tests v3
  graphs/graph/tests/acceptance_tests.rs
Labels: refactoring

#50 Pdo refactoring in acceptance tests v4
  graphs/graph/tests/acceptance_tests.rs
Labels: refactoring

#58 Test refactoring & some clean up
  graphs/runner/src/bin/main.rs
  graphs/runner/src/cli.rs
  graphs/runner/src/generate_graph.rs
  graphs/runner/tests/graph_file_generator_subcommands.rs
Labels: refactoring

#69 Issue #65: rename CLI subcommands and parameters
  graphs/runner/src/bin/main.rs
  graphs/runner/src/cli.rs
  graphs/runner/src/generate_graph.rs
  graphs/runner/tests/graph_file_generator_subcommands.rs
Labels: refactoring

#72 Small updates in tests
  graphs/runner/src/generate_graph.rs
  graphs/runner/tests/graph_file_generator_subcommands.rs
Labels: refactoring, test

#82 Add write_app_error_message in main
  graphs/runner/src/main.rs
Labels: enhancement, refactoring

#83 Pdodev some micro adjustments
  graphs/graph/src/errors.rs
  graphs/graph/src/lib.rs
  graphs/graph/src/reader.rs
  graphs/graph/src/structures.rs
  graphs/runner/src/cli.rs
  graphs/runner/src/errors.rs
  graphs/runner/src/generate_graph.rs
  graphs/runner/src/lib.rs
  graphs/runner/src/main.rs
Labels: refactoring
